[project]
name = "cthon"
version = "0.1.0"
description = "Nice wrapper for the ctypes module."
readme = "README.md"
requires-python = ">=3.13"
license = { file = "LICENSE" }
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
